version: '3.0'
services:
  ui:
    image: joxit/docker-registry-ui:static
    ports:
      - 8080:80
    environment:
      - REGISTRY_TITLE=My Private Docker Registry
      - REGISTRY_URL=https://registry.persival.ir:5000
    networks:
      - registry-ui-net

networks:
  registry-ui-net:
